export interface Appointment {
  id?: number; // Optional because new appointments won't have an ID yet
  appointmentDate: string; // ISO format (YYYY-MM-DD)
  appointmentTime: string; // Format (HH:mm:ss)
  serviceId: number;
  status: 'PENDING' | 'COMPLETED' | 'CANCELLED'; // Matches your SQL default and constraints
  totalPrice: number;
  createdAt?: string; // Generated by DB
  employeeId: number | null; // Can be null until a provider is assigned
  customerId: number;
}

export interface Customer {
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
}

export interface Employee {
  id: number;
  firstName: string;
  lastName: string;
  specialization: string;
}

export interface AppointmentCardProps {
  customer: Customer;
  serviceName: string;
  totalCost: number;
  status: string;
  availableEmployees: Employee[];
}