spring.application.name=hairstyle
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
management.endpoints.web.exposure.include=*
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.default_schema=hairstyle
spring.jpa.defer-datasource-initialization=true
