spring.datasource.url=jdbc:postgresql://postgres:CzuVAtrHPiwhZLGaEEyfzgSfCNeZHTFB@postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=CzuVAtrHPiwhZLGaEEyfzgSfCNeZHTFB
spring.sql.init.mode=always
