spring.application.name=hairstyle
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres?currentSchema=hairstyle,public
spring.datasource.username=postgres
spring.datasource.password=password123
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update