-- 1. Setup Namespace
DROP SCHEMA hairstyle CASCADE;
CREATE SCHEMA IF NOT EXISTS hairstyle;
SET search_path TO hairstyle, public;

-- 2. Create Sequences
CREATE SEQUENCE IF NOT EXISTS employees_id_seq;
CREATE SEQUENCE IF NOT EXISTS appointments_id_seq;
-- Add services sequence if not using Identity
CREATE SEQUENCE IF NOT EXISTS services_id_seq;

-- 3. Independent Tables (No Foreign Keys)
CREATE TABLE IF NOT EXISTS customers
(
    id            bigint generated by default as identity
    constraint customer_pkey primary key,
    date_of_birth varchar(255) not null,
    email         varchar(255) not null constraint uk_customer_email unique,
    first_name    varchar(255) not null,
    last_name     varchar(255) not null,
    password      varchar(255) not null,
    phone_number  varchar(255) not null
    );
ALTER TABLE customers OWNER TO postgres;

CREATE TABLE IF NOT EXISTS services
(
    id          bigint DEFAULT nextval('services_id_seq'::regclass) PRIMARY KEY,
    name        varchar(255) NOT NULL,
    description text NOT NULL,
    price       numeric(38, 2) NOT NULL,
    duration    varchar(255) NOT NULL,
    image       varchar(255) NOT NULL,
    category    varchar(255) NOT NULL

    );
ALTER TABLE services OWNER TO postgres;

-- 4. Employee Table
CREATE TABLE IF NOT EXISTS employees
(
    id                bigint    DEFAULT nextval('employees_id_seq'::regclass) NOT NULL
    PRIMARY KEY,
    first_name        varchar(255)                                            NOT NULL,
    last_name         varchar(255)                                            NOT NULL,
    email             varchar(255)                                            NOT NULL
    UNIQUE,
    phone_number      varchar(255),
    specialization    varchar(255),
    bio               text,
    profile_image_url text,
    is_active         boolean   DEFAULT true,
    created_at        timestamp DEFAULT CURRENT_TIMESTAMP,
    date_of_birth     varchar(255)                                            NOT NULL,
    password          varchar(255)                                            NOT NULL,
    title             varchar(255)                                            NOT NULL
    );
ALTER TABLE employees OWNER TO postgres;

-- 5. Appointments Table (References Customers, Employees, and Services)
CREATE TABLE IF NOT EXISTS appointments
(
    id               bigint       DEFAULT nextval('appointments_id_seq'::regclass) NOT NULL
    PRIMARY KEY,
    appointment_date date                                                          NOT NULL,
    appointment_time time                                                          NOT NULL,
    service_id       bigint       REFERENCES services(id),
    status           varchar(255) DEFAULT 'PENDING',
    total_price      numeric(38, 2),
    created_at       timestamp    DEFAULT CURRENT_TIMESTAMP,
    employee_id      bigint       CONSTRAINT fk_employee REFERENCES employees(id),
    customer_id      bigint       REFERENCES customers(id)

    );
ALTER TABLE appointments OWNER TO postgres;